apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: helloworld.default.svc.cluster.local # 匹配helloworld ip
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
    loadBalancer:
      simple: ROUND_ROBIN
      localityLbSetting:
        enabled: true
        failoverPriority:
          - "topology.kubernetes.io/region"
          - "topology.kubernetes.io/zone"
          - "topology.istio.io/subzone"
        # Distribute: https://github.com/rocketlawyer/flagger/blob/7ab0eb14ea5a987296c160ad54ca4c9a79d1488f/pkg/apis/istio/v1alpha3/destination_rule.go#L123
        #   - from : ""
        #   to: ""
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 1m