apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-region1.zone2-1
  labels:
    app: helloworld
    version: region1.zone2-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: region1.zone2-1
  template:
    metadata:
      labels:
        app: helloworld
        version: region1.zone2-1
    spec:
      containers:
      - name: helloworld
        env:
        - name: SERVICE_VERSION
          value: region1.zone2-1
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      nodeSelector:
        kubernetes.io/hostname: c1-worker2
