kubectl apply -f destination.yaml
kubectl apply -f sleep-c1-w3.yaml
kubectl apply -f helloworld-srv.yaml
kubectl apply -f helloworld-region1.zone1-1.yaml
kubectl apply -f helloworld-region1.zone1-2.yaml
kubectl apply -f helloworld-region1.zone2-1.yaml
kubectl apply -f helloworld-region1.zone2-2.yaml
kubectl apply -f helloworld-region2.zone3-1.yaml
kubectl apply -f helloworld-region2.zone3-2.yaml